<?php

namespace CrCms\Server\Drivers\Laravel\WebSocket;

use CrCms\Server\Drivers\Laravel\Http\Server as HttpServer;
use CrCms\Server\Server\ServerFactory;
use Swoole\Server as SwooleServer;

class Server extends HttpServer
{
    /**
     * Create websocket server
     *
     * @return SwooleServer
     */
    public function create(): SwooleServer
    {
        // TODO: Change the autogenerated stub
        return ServerFactory::factory('websocket', $this->baseConfig);
    }
}