<?php

namespace CrCms\Server\Tests\Laravel;

use CrCms\Server\Drivers\Laravel\Contracts\ApplicationContract;
use Illuminate\Contracts\Container\Container;
use CrCms\Server\Drivers\Laravel\Application as BaseApplication;

class Application extends BaseApplication implements ApplicationContract
{
    protected function createApplication(): Container
    {
        // TODO: Change the autogenerated stub
        $container = new \Illuminate\Container\Container();

        $container->bind('bind_test',function(){
            return new \stdClass();
        });

        $container->singleton('singleton_test',function(){
            return new \stdClass();
        });

        $container->instance('instance_test',new \stdClass());

        return $container;

    }
}