<?php

namespace CrCms\Server\Tests\Laravel;


use Illuminate\Contracts\Container\Container;
use PHPUnit\Framework\TestCase;

class ApplicationTest extends TestCase
{
    /**
     * @var Container
     */
    protected static $app;

    public static function setUpBeforeClass()
    {
        // TODO: Change the autogenerated stub
        parent::setUpBeforeClass();

        static::$app = require 'bootstrap.php';
    }

    public function testApplication()
    {
//        $application1 = new \CrCms\Server\Drivers\Laravel\Application(static::$app->make('config')->get('swoole'));

        $application = \Mockery::mock(\CrCms\Server\Drivers\Laravel\Application::class);
        $application->shouldAllowMockingProtectedMethods();

        $application->shouldReceive('createApplication')->andReturn(new \Illuminate\Container\Container());
        $application->shouldReceive('app')->andReturn(new \Illuminate\Container\Container());

        $hash1 = spl_object_hash($application->app());
        $hash2 = spl_object_hash($application->app());

        $this->assertEquals($hash1, $hash2);
    }

}