<?php

namespace CrCms\Server\Tests\Laravel\Http;

use CrCms\Server\Drivers\Laravel\Http\Request;
use PHPUnit\Framework\TestCase;

/**
 * Class RequestTest.
 */
class RequestTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRequest()
    {
        $swooleRequest = \Mockery::mock('Swoole\Http\Request');
        $swooleRequest->shouldReceive('rawContent')->andReturn(json_encode(['zzz'=>'x']));
        $swooleRequest->server = ['request_uri' => '/abc', 'request_method'=>'post'];
        $swooleRequest->header = ['content-type' => 'text/html'];
        $swooleRequest->files = [];
        $swooleRequest->cookie = [];
        $swooleRequest->post = ['z' => 1];
        $swooleRequest->get = ['x' => 1];

        $request = new Request($swooleRequest);

        $illuminateRequest = $request->getIlluminateRequest();

        $this->assertInstanceOf(\Illuminate\Http\Request::class, $illuminateRequest);
        $this->assertArrayHasKey('x', $illuminateRequest->all());
        $this->assertEquals(1, $illuminateRequest->input('x'));
        $this->assertEquals(1, $illuminateRequest->input('z'));
        $this->assertEquals('/abc', $illuminateRequest->server->get('REQUEST_URI'));
        $this->assertEquals('text/html', $illuminateRequest->header('content-type'));
    }
}
